// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUfrv8Un44A_mqHDB771WEnVmJYVCf590',
    appId: '1:592122912607:web:7d8381ebc54207d33120ea',
    messagingSenderId: '592122912607',
    projectId: 'instagram-clone-44674',
    authDomain: 'instagram-clone-44674.firebaseapp.com',
    storageBucket: 'instagram-clone-44674.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUaOJCDp1mwzyFTV9oubeawrn6xCOzRMc',
    appId: '1:592122912607:android:04dc0ceae814cc3d3120ea',
    messagingSenderId: '592122912607',
    projectId: 'instagram-clone-44674',
    storageBucket: 'instagram-clone-44674.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlilYS-90zT_b2qhamyD2gjZk19pXyc2w',
    appId: '1:592122912607:ios:bcdafc4cb25529c83120ea',
    messagingSenderId: '592122912607',
    projectId: 'instagram-clone-44674',
    storageBucket: 'instagram-clone-44674.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
